# Generated by Django 5.1.13 on 2025-10-07 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion_tarea',
            name='tarea',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clase.tarea'),
        ),
        migrations.AddField(
            model_name='asignacion_tarea',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clase.usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clase.usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='tarea',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clase.tarea'),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='tarea',
            field=models.ManyToManyField(to='clase.tarea'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='colaboradores',
            field=models.ManyToManyField(to='clase.usuario'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='creador', to='clase.usuario'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='creador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clase.usuario'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clase.proyecto'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuarios_asignados',
            field=models.ManyToManyField(related_name='usuarios_asignados', through='clase.Asignacion_tarea', to='clase.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
