# Generated by Django 5.1.13 on 2025-10-07 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0002_asignacion_tarea_tarea_asignacion_tarea_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creador', to='clase.usuario'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'PENDIENTE'), ('PROGRESO', 'Progreso'), ('COMPLETADA', 'Completada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
