# Generated by Django 5.1.13 on 2025-10-07 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0003_alter_proyecto_creador_alter_tarea_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion_tarea',
            name='tarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clase.tarea'),
        ),
        migrations.AlterField(
            model_name='asignacion_tarea',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clase.usuario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clase.usuario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clase.tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clase.usuario'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROGRESO', 'Progreso'), ('COMPLETADA', 'Completada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clase.proyecto'),
        ),
    ]
